### ISSUE TITLE
makesig: Instruction.getNext() may not correspond to adjacent offset

### ISSUE THREAD

**Issue by nosoop** [nosoop/ghidra_scripts#1]
Tested against `CEconItemSchema::AssignDefaultBodygroupState + 0x101` in TF2.  Signature generation passes the return and runs into some bytes being treated as alignment.

Thinking we should just check for adjacency before `ins.getNext()`:
```python
if ins.getNext().getAddress().getOffset() != ins.getAddress().getOffset() + ins.length:
	raise Exception("Instruction.getNext() returned non-adjacent byte")
```

**Comment by sohpeach** [comment]
I can share a simple fix for this if you license the project

**Comment by nosoop** [comment]
Sure; that's not a problem.  I've gone ahead and pushed the BSD Zero Clause license.
