### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by YaLTeR** [nosoop/ghidra_scripts#2]
Hello, could you please add a license (GPL3 or MIT or public domain idk)? I want to modify the script for my purposes and distribute the modified version and I can't really do that without a license.

**Comment by nosoop** [comment]
Ah, sorry for the delay; didn't realize there would be issues filed in this repository and I stopped watching.

I've gone ahead and pushed the BSD Zero-Clause license; feel free to use the script(s) as you'd like.

**Comment by YaLTeR** [comment]
Cheers!
